### ISSUE TITLE
Iteration Plan: Spring/Summer 2021

### ISSUE THREAD

**Issue by johnbillion** [johnbillion/query-monitor#594]
This plan captures the current high level goals for Query Monitor. The list might change over time and the next plan will start later in 2021.

This plan isn't tied to any particular releases. Other bug fixes will be included in releases but aren't necessarily listed here.

## Previous Iteration Retro

In short, I didn't make a huge amount of progress on the high-level items listed in #539 but I did end up working on some additional new features and bug fixes which were needed for client projects, mainly #551 and #589. Happy with what I got done in recent months, it just wasn't very well aligned with the plan.

I need to strictly prioritise the `QM_Backtrace` fixes (#564) because there's now lots of duplicated stack trace processing across the collectors and outputters, and that reduces the reliability and consistency of stack traces.

Similarly, the object cache statistics standards (#518) needs prioritising so QM can show consistent object cache stats from various cache drivers.

I'm de-prioritising the 404 helper (#342) and `WP_Error` tracking (#559) because in practice they're proving to be not as useful as I expected, at least in their current state. Both need more work.

I unexpectedly made more progress on the client-side rendering branch than I planned (#483) but this is a slow-burner and is a long way from nearing being ready. I'll continue to work on this as and when I have the time and enthusiasm.

## Priority Fixes

* [ ] Make `QM_Backtrace` more resilient, reliable, add tests - #564
  - [x] #495
  - [x] #494 
  - [x] #461 
  - [x] #433 
  - [ ] #340 

## New Panels

* [ ] Object cache statistics standard #518

## General Features

* [x] Ability for code partway through a request to prevent QM's output - #590

## Performance and Dependencies

* [ ] Limit the number of HTTP headers for PHP errors that occur during Ajax, REST API, etc #275 

## WordPress Core Tasks

None planned

## Meta

None

## Ongoing

Long (long) term work which is in progress or in idea stage but will not ship soon

* [ ] Implement client side rendering 🚀 - #483
* [ ] Hook inspection
* [ ] Component insights
* [ ] Flow explorer
* [ ] Document all the actions and filters

**Comment by jchimene** [comment]
Hi - Have you considered this as a must-use plugin that sends logs to syslog? I'm working on a particularly nasty hack on a website. This plugin loads at the right time, and can log code and database events.
